name: LCAcollect App CI/CD Workflow

on:
  push:
    branches:
      - main
      - stage
  pull_request:
    branches:
      - main
      - stage
  workflow_dispatch:

jobs:
  test:
    uses: lcacollect/.github/.github/workflows/test-npm.yaml@main
    with:
      router_url: ${{ (github.ref_name == 'main' && 'https://api.lcacollect.dk/graphql') || 'https://api.test.lcacollect.dk/graphql' }}
      artifact_name: 'lcacollect-app'
      run_e2e: false
      aad_client_id: ${{ vars.VITE_AAD_CLIENT_ID }}
      aad_tenant_id: ${{ vars.VITE_AAD_TENANT_ID }}
      aad_app_client_id: ${{ vars.VITE_AAD_APP_CLIENT_ID }}
    secrets: inherit

  publish:
    if: github.event_name != 'pull_request'
    uses: lcacollect/.github/.github/workflows/publish-app.yaml@main
    needs:
      - test
    with:
      artifact_name: 'lcacollect-app'
      storage_account: ${{ (github.ref_name == 'main' && vars.PRODUCTION_STORAGE_ACCOUNT) || vars.DEVELOPMENT_STORAGE_ACCOUNT }}
      container_name: ${{ vars.AZURE_CONTAINER_NAME }}
    secrets:
      azure_credentials: ${{ (github.ref_name == 'main' && secrets.AZURE_CREDENTIALS) || secrets.AZURE_CREDENTIALS_DEV }}
